# This runs the tests for the unreleased Scrapy master branch.
# It doesn't run by default, to run it label your PR with the "test-scrapy-unreleased" label.
name: scrapy-unreleased

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'test-scrapy-unreleased')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Python 3.13
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: tox
      run: |
        tox -e scrapy-unreleased -- -n auto
    - name: coverage
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
